### ISSUE TITLE
Fixture UniqueConstraintViolation when loading related fixutres

### ISSUE THREAD

**Issue by chrisnicola** [jeremyevans/fixture_dependencies#22]
It seems as if the fixtures are attempting to be reloaded into the database when any references are loaded. When I do the following:

```
user = fixture(user__first)
account = fixture(account_first)
```

In `users.yml` I have:
```
first:
  email: 'john.doe@company.test'
```

In `accounts.yml` I have
```
first:
  user: first
```

And the error I get is on the second line where the account fixture is loaded:

```

Sequel::UniqueConstraintViolation: PG::UniqueViolation: ERROR:  duplicate key value violates unique constraint "users_email_unique"
DETAIL:  Key (email)=(john.doe@company.test) already exists.

```

I can probably put together a trivial example to test but before I go setting up a clean room I just wanted to ask if I've done something insanely wrong in my usage.

For now I can just access the user by loading the dependent fixture and getting it from there. but this behaviour seems like it wasn't intended to me, so I wanted to confirm that.

**Comment by jeremyevans** [comment]
If I had to guess, you are getting this because you are not setting a primary key on the fixtures.  The first thing you should try is adding a unique primary key value for each fixture, e.g.:

```yaml
first:
  id: 1
  user: first
```

If that doesn't fix your issue, do you get the same error if you do this?:

```ruby
user = FixtureDependencies.load(:user__first)
account = FixtureDependencies.load(:account__first)
```

If you get the same error, please put together a minimal self contained example reproducing the error and I will attempt to debug.  If you do not get the same error, the problem is probably in your code.

**Comment by chrisnicola** [comment]
@jeremyevans ah thanks for that. I did not realize it had to be set manually. I'm used to AR's fixtures which handle PKs transparently. It isn't a big deal though, in fact I prefer the idea of having a declared, fixed ID for fixtures in tests 👍
