### ISSUE TITLE
fixture filenames with tables in other databases

### ISSUE THREAD

**Issue by roupen** [jeremyevans/fixture_dependencies#23]
In my app I have 2 databases with tables. Let's say the two databases are "common_dev" and "primary_dev" on my development environment.  On my CI environment these two databases are "common_test" and "primary_test". Sequel is connected to the primary_dev database. So when I want to make a fixture on a model for the common_dev database it expects I create a file like: "common_dev__user.yml". This becomes a problem when the app gets run through CI because now the file it's looking for will be "common_test__user.yml" which doesn't exist. Is there something similar to `class_map` that can be like `file_map` so we can override a model's use of table name to determine fixture file?

**Comment by jeremyevans** [comment]
There isn't anything that currently handles this in fixture_dependencies.  However, you can probably work around the issue using:

```ruby
def User.table_name
  :user
end
```

That may have other effects though.  I guess we could have fixture_dependencies see if the model class responds to a `fixture_filename` class method, and use that instead of `table_name` if it is defined.  Do you want to work on a patch for that?

**Comment by roupen** [comment]
Sure I'll give it a whirl later today and open a PR when I come up with something, thanks!

**Comment by jeremyevans** [comment]
Closing this as it is being worked on in #24.
