### ISSUE TITLE
Hard coded primary keys that are auto incrementing

### ISSUE THREAD

**Issue by davekaro** [jeremyevans/fixture_dependencies#34]
This may not be an actual issue, but more asking for clarification. The README [states](https://github.com/jeremyevans/fixture_dependencies/blob/ba959cf4ebbd73a81212f56a96157e304e2aebb7/README.md?plain=1#L156-L158):

> Note that you make sure to hard code primary key values for each fixture, as shown in the example above.

However, when I did this and subsequently attempted to `INSERT` a row to the database during test, I ran into conflicting primary keys (`PG::UniqueViolation: ERROR:  duplicate key value violates unique constraint`). I am guessing this is because the primary key sequence wasn't reset after manually specifying the keys in the fixture file. There is [code](https://github.com/jeremyevans/fixture_dependencies/blob/ba959cf4ebbd73a81212f56a96157e304e2aebb7/lib/fixture_dependencies.rb#L263) to handle primary keys not being set in the fixture, so I'm wondering why the README encourages it, and if I should still be setting them, what is a good way to reset the sequences?

**Comment by jeremyevans** [comment]
If you don't hard code the fixture primary key value, and attempt to load the fixture a second time, I think it will attempt to create a duplicate row, instead of returning the already created fixture.

In terms of resetting the sequences, on PostgreSQL, `Database#reset_primary_key_sequence` can be used, but it only resets the sequence to more than the current maximum value in the database.  Depending on how you are doing testing, that may not work very well.  Your best bet is probably calling `setval` manually for each sequence with a number greater than the maximum hard coded primary key value.
